/**
 * Auto-generated by `cargo stylus export-abi` from contracts/q2-anchor.
 * The complete public surface of the Q2Anchor contract, nothing else is callable.
 */

// SPDX-License-Identifier: MIT-OR-APACHE-2.0
pragma solidity ^0.8.23;

interface IQ2Anchor {
    // Anchor a commitment: a content hash of an off-chain artifact plus two
    // opaque coarse codes. Permissionless, append-only. Returns the record id.
    function record(bytes32 artifact_hash, uint16 label, uint16 context) external returns (uint256);

    // Total number of anchored records.
    function count() external view returns (uint256);

    // Read a record: (artifact_hash, label, context, submitter, timestamp).
    function get(uint256 id) external view returns (bytes32, uint16, uint16, address, uint64);

    // Does record `id` commit to `artifact_hash`? False for an unknown id.
    function verify(uint256 id, bytes32 artifact_hash) external view returns (bool);

    error RecordNotFound();

    // event Recorded(uint256 indexed id, address indexed submitter,
    //                bytes32 artifact_hash, uint16 label, uint16 context, uint64 timestamp);
}
