#!/usr/bin/env python3
"""Fully-recursive Karatsuba multiplier generator.

Unlike gen.py (one level, sub-products left as `*`), this recurses all the way
down to a small schoolbook base case, so the design realizes the algorithm's
asymptotic complexity: gate count and area scale as Theta(n^log2 3) ~ n^1.585,
not the schoolbook Theta(n^2). That is the divergence a linear-scale plot shows.

Each module km<w> is a square w x w -> 2w multiplier. w <= BASE is the schoolbook
base case (`assign p = a*b`, i.e. what the tool synthesizes). Above it, one
Karatsuba step: three sub-multiplies (a0*b0, a1*b1, (a0+a1)*(b0+b1)) plus the
recombination adds. Attribution: Karatsuba & Ofman (1962).

Run:  python3 karat_recursive.py 8 16 32 64 128
      -> rec_8.v ... rec_128.v (each self-contained; top module km<w>)
"""
import sys

BASE = 4  # w <= BASE bottoms out in schoolbook a*b

def needed(w, acc):
    if w in acc:
        return
    acc.add(w)
    if w <= BASE:
        return
    H = w // 2
    hi = w - H
    for sw in (H, hi, hi + 1):
        needed(sw, acc)

def module(w):
    L = []
    name = f"km{w}"
    if w <= BASE:
        L.append(f"module {name}(input [{w-1}:0] a, input [{w-1}:0] b, "
                 f"output [{2*w-1}:0] p);")
        L.append("  assign p = a * b;")
        L.append("endmodule")
        return "\n".join(L)
    H = w // 2
    hi = w - H
    z0w, z2w, z3w = 2 * H, 2 * hi, 2 * (hi + 1)
    L.append(f"// {w}-bit Karatsuba step: split at bit {H} "
             f"(low {H} bits, high {hi} bits)")
    L.append(f"module {name}(input [{w-1}:0] a, input [{w-1}:0] b, "
             f"output [{2*w-1}:0] p);")
    L.append(f"  wire [{H-1}:0] a0 = a[{H-1}:0];")
    L.append(f"  wire [{hi-1}:0] a1 = a[{w-1}:{H}];")
    L.append(f"  wire [{H-1}:0] b0 = b[{H-1}:0];")
    L.append(f"  wire [{hi-1}:0] b1 = b[{w-1}:{H}];")
    L.append(f"  wire [{z0w-1}:0] z0;")
    L.append(f"  wire [{z2w-1}:0] z2;")
    L.append(f"  km{H} u0(.a(a0), .b(b0), .p(z0));")
    L.append(f"  km{hi} u2(.a(a1), .b(b1), .p(z2));")
    L.append(f"  wire [{hi}:0] sa = a0 + a1;")
    L.append(f"  wire [{hi}:0] sb = b0 + b1;")
    L.append(f"  wire [{z3w-1}:0] z3;")
    L.append(f"  km{hi+1} u3(.a(sa), .b(sb), .p(z3));")
    L.append(f"  wire [{z3w-1}:0] z1 = z3 - z0 - z2;")  # = a0*b1 + a1*b0, >= 0
    L.append(f"  wire [{2*w-1}:0] pz0 = z0;")
    L.append(f"  wire [{2*w-1}:0] pz1 = z1;")
    L.append(f"  wire [{2*w-1}:0] pz2 = z2;")
    L.append(f"  assign p = (pz2 << {2*H}) + (pz1 << {H}) + pz0;")
    L.append("endmodule")
    return "\n".join(L)

if __name__ == "__main__":
    tops = [int(x) for x in sys.argv[1:]] or [8, 16, 32, 64, 128]
    for W in tops:
        acc = set()
        needed(W, acc)
        mods = "\n\n".join(module(w) for w in sorted(acc, reverse=True))
        with open(f"rec_{W}.v", "w") as f:
            f.write(f"// Fully-recursive Karatsuba, top width {W}. "
                    f"Base case schoolbook at w<={BASE}.\n")
            f.write(f"// Attribution: Karatsuba & Ofman (1962). "
                    f"Generated by karat_recursive.py.\n\n")
            f.write(mods + "\n")
        print(f"rec_{W}.v: top km{W}, {len(acc)} distinct sub-widths")
