#!/usr/bin/env python3
"""Generate a W-bit adder in four architectures, each with carry-in and
carry-out (2W+1 inputs, W+1 outputs). All share the port signature
(a, b, cin -> s, cout), so any pair can be checked equivalent by a miter.

  add_default : `assign {cout,s} = a + b + cin;`  -- what Yosys synthesizes.
  add_ripple  : structural ripple-carry, a chain of full adders. O(n) depth.
  add_ks      : Kogge-Stone parallel-prefix adder. O(log n) depth, O(n log n)
                cells. Attribution: P. M. Kogge and H. S. Stone, IEEE Trans.
                Computers C-22(8):786-793, 1973.
  add_bk      : Brent-Kung parallel-prefix adder. O(log n) depth, O(n) cells.
                Attribution: R. P. Brent and H. T. Kung, IEEE Trans. Computers
                C-31(3):260-264, 1982.

Prefix framework: bit generate g[i]=a[i]&b[i], propagate p[i]=a[i]^b[i]; the
associative operator (G,P) o (G',P') = (G | P&G', P&P') builds group
generate/propagate; carry into bit i is c[i]=G[i-1:0] | (P[i-1:0] & cin);
sum s[i]=p[i]^c[i]. Only the prefix NETWORK differs between KS and BK.

Run:  python3 add_gen.py 8 16 32 64   -> add_8.v ... add_64.v
"""
import sys, math

def m_default(W):
    return (f"module add_default(input [{W-1}:0] a, input [{W-1}:0] b, input cin,\n"
            f"  output [{W-1}:0] s, output cout);\n"
            f"  assign {{cout, s}} = a + b + cin;\n"
            f"endmodule\n")

def m_ripple(W):
    L = [f"module add_ripple(input [{W-1}:0] a, input [{W-1}:0] b, input cin,",
         f"  output [{W-1}:0] s, output cout);",
         f"  wire [{W}:0] c;",
         f"  assign c[0] = cin;"]
    for i in range(W):
        L.append(f"  assign s[{i}] = a[{i}] ^ b[{i}] ^ c[{i}];")
        L.append(f"  assign c[{i+1}] = (a[{i}] & b[{i}]) | (c[{i}] & (a[{i}] ^ b[{i}]));")
    L.append(f"  assign cout = c[{W}];")
    L.append("endmodule")
    return "\n".join(L) + "\n"

def m_prefix(W, kind, modname):
    body = []
    wc = [0]
    def nw(pref):
        n = f"{pref}{wc[0]}"; wc[0] += 1; return n
    pbit = [f"p{i}" for i in range(W)]     # fixed bit-propagate, used for the sum
    G = [f"g{i}" for i in range(W)]         # mutable group-generate
    P = [f"p{i}" for i in range(W)]         # mutable group-propagate
    L = [f"module {modname}(input [{W-1}:0] a, input [{W-1}:0] b, input cin,",
         f"  output [{W-1}:0] s, output cout);"]
    for i in range(W):
        body.append(f"  wire g{i} = a[{i}] & b[{i}];")
        body.append(f"  wire p{i} = a[{i}] ^ b[{i}];")
    def op(ihi, ilo):
        ng, np = nw("G"), nw("P")
        body.append(f"  wire {ng} = {G[ihi]} | ({P[ihi]} & {G[ilo]});")
        body.append(f"  wire {np} = {P[ihi]} & {P[ilo]};")
        G[ihi], P[ihi] = ng, np
    if kind == "ks":
        D = 1
        while D < W:
            for i in range(W - 1, D - 1, -1):   # high->low: reads old lower values
                op(i, i - D)
            D *= 2
    elif kind == "bk":
        d = 1                                    # up-sweep (reduce)
        while d < W:
            i = 2 * d - 1
            while i < W:
                op(i, i - d)
                i += 2 * d
            d *= 2
        d = W // 4                               # down-sweep (fill)
        while d >= 1:
            i = 3 * d - 1
            while i < W:
                op(i, i - d)
                i += 2 * d
            d //= 2
    # G[i],P[i] are now the group prefix over [i:0]
    body.append(f"  wire [{W}:0] c;")
    body.append(f"  assign c[0] = cin;")
    for i in range(1, W):
        body.append(f"  assign c[{i}] = {G[i-1]} | ({P[i-1]} & cin);")
    body.append(f"  assign cout = {G[W-1]} | ({P[W-1]} & cin);")
    for i in range(W):
        body.append(f"  assign s[{i}] = {pbit[i]} ^ c[{i}];")
    body.append("endmodule")
    return "\n".join(L + body) + "\n"

if __name__ == "__main__":
    widths = [int(x) for x in sys.argv[1:]] or [8, 16, 32, 64]
    for W in widths:
        with open(f"add_{W}.v", "w") as f:
            f.write(f"// {W}-bit adders, four architectures. Generated by add_gen.py.\n")
            f.write(m_default(W) + "\n")
            f.write(m_ripple(W) + "\n")
            f.write(m_prefix(W, "ks", "add_ks") + "\n")
            f.write(m_prefix(W, "bk", "add_bk") + "\n")
        print(f"add_{W}.v: default, ripple, ks (Kogge-Stone), bk (Brent-Kung)")
